.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/task.md, .github/PULL_REQUEST_TEMPLATE.md
Issue 15: Set up pull request templates
Added issue and pull request templates.
=> Issue 14: Set up issue templates

pom.xml, src/test/java/org/carlspring/cloud/storage/s3fs/FileSystemProvider/NewFileSystemIT.java, src/test/java/org/carlspring/cloud/storage/s3fs/FileSystemProvider/NewFileSystemTest.java, src/test/java/org/carlspring/cloud/storage/s3fs/S3IteratorTest.java, src/test/java/org/carlspring/cloud/storage/s3fs/S3UnitTestBase.java
=> Issue 7: Update all Maven dependencies to their latest versions

.github/workflows/build.yml, pom.xml
=> issue-76: Improve github build

src/test/java/org/carlspring/cloud/storage/s3fs/AmazonS3ClientIT.java, src/test/java/org/carlspring/cloud/storage/s3fs/FileSystemProvider/ReadAttributesTest.java, src/test/java/org/carlspring/cloud/storage/s3fs/FilesIT.java, src/test/java/org/carlspring/cloud/storage/s3fs/Path/EndsWithTest.java, src/test/java/org/carlspring/cloud/storage/s3fs/S3UtilsIT.java, src/test/java/org/carlspring/cloud/storage/s3fs/spike/InstallProviderTest.java, src/test/java/org/carlspring/cloud/storage/s3fs/spike/ProviderSpecTest.java, src/test/java/org/carlspring/cloud/storage/s3fs/util/CopyDirVisitor.java
This pull request closes #53  .
=> Issue 53: Translate all comments, methods, vars, etc that are in Spanish into English

src/test/java/org/carlspring/cloud/storage/s3fs/S3UtilsIT.java
This pull request closes #57 .
=> Issue 57: Rename all test methods that don't conform with the camel Case convention

CODE-OF-CONDUCT.md, CONTRIBUTING.md
This pull request fixes documentation issues, as discussed in the chat.
=> Fix links to documentation

src/main/java/org/carlspring/cloud/storage/s3fs/S3FileChannel.java, src/main/java/org/carlspring/cloud/storage/s3fs/S3FileSystemProvider.java, src/test/java/org/carlspring/cloud/storage/s3fs/S3FileChannelTest.java, src/test/java/org/carlspring/cloud/storage/s3fs/fileSystemProvider/NewAsynchronousFileChannelTest.java, src/test/java/org/carlspring/cloud/storage/s3fs/fileSystemProvider/NewAsynchronousFileChannelTestIT.java
This pull request closes #99 .
=> Issue 99: Switch the NIO implementation to use AsynchronousFileChannel instead of FileChannel

docs/content/reference/configuration-options.md, docs/content/reference/examples/basic-example.md, src/main/java/org/carlspring/cloud/storage/s3fs/S3Factory.java, src/main/java/org/carlspring/cloud/storage/s3fs/S3FileSystemProvider.java, src/main/java/org/carlspring/cloud/storage/s3fs/S3Path.java, src/test/java/org/carlspring/cloud/storage/s3fs/util/EnvironmentBuilder.java, src/test/resources/amazon-test-sample.properties
This pull request closes #136.
=> Issue 136: Convert the configuration properties to use dots instead of underscores

pom.xml
=> Issue 42: Upgrade com.github.marschall:memoryfilesystem to 2.1.0

pom.xml
This pull request closes #150.
cc: @electricsam 
=> Issue 150: Remove dependency on logback-classic

docs/content/contributing/code-of-conduct.md, docs/content/contributing/developer-guide/coding-convention.md, docs/content/contributing/developer-guide/index.md, docs/content/contributing/legal/ICLA.md, docs/content/contributing/legal/index.md, docs/content/history.md, docs/mkdocs.yml
This pull request closes #170 
=> issue-170: Fix broken documentation links

src/main/java/org/carlspring/cloud/storage/s3fs/S3SeekableByteChannel.java, src/test/java/org/carlspring/cloud/storage/s3fs/S3SeekableByteChannelTest.java
This pull request closes #167.
=> Issue 167: Allow long file names to be uploaded to S3

.github/workflows/build.yml, pom.xml, src/test/java/org/carlspring/cloud/storage/s3fs/FileSystemsIT.java, src/test/java/org/carlspring/cloud/storage/s3fs/FilesIT.java, src/test/java/org/carlspring/cloud/storage/s3fs/S3ClientIT.java, src/test/java/org/carlspring/cloud/storage/s3fs/S3UtilsIT.java, src/test/java/org/carlspring/cloud/storage/s3fs/fileSystemProvider/GetFileSystemIT.java, src/test/java/org/carlspring/cloud/storage/s3fs/fileSystemProvider/NewFileSystemIT.java, src/test/java/org/carlspring/cloud/storage/s3fs/junit/examples/CombinedIT.java, src/test/java/org/carlspring/cloud/storage/s3fs/junit/examples/CombinedMinioS3IT.java, src/test/java/org/carlspring/cloud/storage/s3fs/junit/examples/CombinedS3MinioIT.java, src/test/java/org/carlspring/cloud/storage/s3fs/junit/examples/MinioClassAnnotationIT.java, src/test/java/org/carlspring/cloud/storage/s3fs/junit/examples/MinioMethodAnnotationIT.java, src/test/java/org/carlspring/cloud/storage/s3fs/junit/examples/S3ClassAnnotationIT.java, src/test/java/org/carlspring/cloud/storage/s3fs/junit/examples/S3MethodAnnotationIT.java, src/test/java/org/carlspring/cloud/storage/s3fs/path/ToURLIT.java, src/test/java/org/carlspring/cloud/storage/s3fs/spike/EnvironmentIT.java, src/test/java/org/carlspring/cloud/storage/s3fs/util/BaseIntegrationTest.java, src/test/java/org/carlspring/cloud/storage/s3fs/util/EnvironmentBuilder.java, src/test/java/org/carlspring/cloud/storage/s3fs/util/MinioContainer.java, src/test/java/org/carlspring/cloud/storage/s3fs/util/S3EndpointConstant.java
This pull request has initial work for #60.
=> Issue-60: Set up testcontainers

docs/content/contributing/developer-guide/index.md
=> Added steps for running IT with MinIO in the documentation.

src/main/java/org/carlspring/cloud/storage/s3fs/S3AwsRegionProviderChain.java, src/main/java/org/carlspring/cloud/storage/s3fs/S3Factory.java, src/test/java/org/carlspring/cloud/storage/s3fs/S3AwsRegionProviderChainTest.java, src/test/resources/config-test
This pull request closes #100.
=> Issue 100: Create a custom provider for AwsRegionProviderChain

.github/workflows/bump-snapshot-version.yaml, .github/workflows/command-dispatcher.yaml, .github/workflows/command-help.yaml, .github/workflows/command-merge-release.yaml, .github/workflows/command-merge-snapshot.yaml, .github/workflows/prepare-release.yaml
=> Incorrect change logs are auto-generated in release prs

src/main/java/org/carlspring/cloud/storage/s3fs/S3OutputStream.java, src/test/java/org/carlspring/cloud/storage/s3fs/S3OutputStreamTest.java
Should check closed when multi thread in synchronized block so that stream won't be closed twice.
=> fix:check closed in synchronized block when multi thread.

src/main/java/org/carlspring/cloud/storage/s3fs/S3FileSystem.java
=> split should be enough

.github/workflows/build.yml, build.gradle.kts, src/test/java/org/carlspring/cloud/storage/s3fs/AttributesUtilsTest.java, src/test/java/org/carlspring/cloud/storage/s3fs/CacheTest.java, src/test/java/org/carlspring/cloud/storage/s3fs/S3FileAttributesTest.java, src/test/java/org/carlspring/cloud/storage/s3fs/path/S3PathTest.java, src/test/java/org/carlspring/cloud/storage/s3fs/spike/FileStoreTest.java, src/test/java/org/carlspring/cloud/storage/s3fs/spike/PathSpecTest.java, src/test/java/org/carlspring/cloud/storage/s3fs/spike/ProviderSpecTest.java, src/test/java/org/carlspring/cloud/storage/s3fs/spike/SpecTest.java, src/test/java/org/carlspring/cloud/storage/s3fs/spike/URISpikeTest.java
=> chore: JUnit5 test classes and methods should have default package visibility

src/test/java/org/carlspring/cloud/storage/s3fs/S3FileStoreTest.java, src/test/java/org/carlspring/cloud/storage/s3fs/S3UtilsIT.java
=> chore: Fix sonar bug reports.

build.gradle.kts
This pull request merges the two configurations of the `jar` gradle task in `build.gradle.kts`.
=> chore(gradle): Merge `jar` task configuration in build.gradle.kts

src/main/java/org/carlspring/cloud/storage/s3fs/S3FileSystemProvider.java, src/main/java/org/carlspring/cloud/storage/s3fs/S3FilteredIterator.java, src/test/java/org/carlspring/cloud/storage/s3fs/fileSystemProvider/NewDirectoryStreamTest.java
This pull request closes #380.
=> Support filtered DirectoryStream

.github/workflows/build.yml, README.md, docs/content/contributing/developer-guide/index.md, src/test/java/org/carlspring/cloud/storage/s3fs/spike/InstallProviderTest.java
This pull request closes #689 
=> Add JDK17 to the build matrix

.github/workflows/build.yml
=> Fix Sonar publishing by moving reports from JDK 11 to JDK 17.

.github/workflows/build.yml
=> Fix publishing snapshots for master branch.

.github/workflows/docs.yaml
=> Migrate to docker compose instead of deprecated docker-compose

.github/workflows/build.yml, README.md, src/main/java/org/carlspring/cloud/storage/s3fs/attribute/S3BasicFileAttributeView.java, src/main/java/org/carlspring/cloud/storage/s3fs/attribute/S3PosixFileAttributeView.java
This pull request closes #829 
=> feat: Add support for JDK 21.

build.gradle.kts
This pull request closes #831 
=> build: Fix Sonar report issues

build.gradle.kts, src/test/java/org/carlspring/cloud/storage/s3fs/S3ClientFactoryTest.java, src/test/java/org/carlspring/cloud/storage/s3fs/util/ExposingS3BaseClientBuilder.java, src/test/java/org/carlspring/cloud/storage/s3fs/util/ExposingS3ClientBuilder.java
This pull request closes #859 
=> Upgrade AWS SDK to latest version
